name: Debug Build
on:
  pull_request:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build org.tiqr.authenticator.staging bundle for Play Store upload
      run: ./gradlew bundleDebug
    - name: Sign org.tiqr.authenticator.staging bundle with developer key for Play Store upload
      id: sign_aab
      uses: ilharp/sign-android-release@v2
      with:
        releaseDir: app/build/outputs/bundle/debug/
        signingKey: ${{ secrets.SIGNINGKEYBASE64 }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
        keyPassword: ${{ secrets.KEYPASSWORD }}
        buildToolsVersion: 35.0.0
    - name: Publish org.tiqr.authenticator.testing to Play Store Internal Test track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_TESTING }}
        packageName: org.tiqr.authenticator.staging
        releaseFiles: ${{ steps.sign_aab.outputs.signedFile }}
        changesNotSentForReview: true
        track: internal
        status: completed
