name: Release Build
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build tiqr app bundle
      run: ./gradlew bundleRelease
    - name: Sign tiqr app Bundle
      id: sign_aab
      uses: ilharp/sign-android-release@v2
      with:
        releaseDir: app/build/outputs/bundle/release/
        signingKey: ${{ secrets.SIGNINGKEYBASE64 }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
        keyPassword: ${{ secrets.KEYPASSWORD }}
        buildToolsVersion: 35.0.0

    - name: Build tiqr apk
      run: ./gradlew assembleRelease
    - name: Sign APK
      id: sign_apk
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release/
        signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
        keyPassword: ${{ secrets.KEYPASSWORD }}
      env:
       BUILD_TOOLS_VERSION: "35.0.0"

    - name: Build Changelog
      id: changelog
      uses: ardalanamini/auto-changelog@v4

    - name: Create Github release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: |
          ${{ steps.changelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Add apk to Github Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.sign_apk.outputs.signedReleaseFile }}
        asset_name: tiqr-${{ github.ref_name }}.apk
        asset_content_type: application/zip

    - name: Publish to play store test track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: org.tiqr.authenticator
        releaseFiles: ${{ steps.sign_aab.outputs.signedFile }}
        track: internal
        status: completed
